# Generated by Django 6.0.4 on 2026-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, help_text='External purchase link (e.g., Amazon, Flipkart)', max_length=500, null=True),
        ),
    ]
